name: ci

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build-linux:
    name: "build on ubuntu-latest"
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: sudo apt-get install libllvm15 llvm-15 llvm-15-dev llvm-15-doc llvm-15-examples llvm-15-runtime
    - run: sudo apt-get install clang-15 clang-tools-15 clang-15-doc libclang-common-15-dev libclang-15-dev libclang1-15 clang-format-15 python3-clang-15 clangd-15 clang-tidy-15
    - run: llvm-config --version
    - run: sudo apt-get install libcurl4-openssl-dev
    - run: make
    
  build-macos:
    name: "build on macos-latest"
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: brew install llvm@15 && brew link llvm@15

    - run: llvm-config --version
    - run: make
