name: ci

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build-linux:
    name: "build on ubuntu-latest"
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install LLVM/Clang 15
      run: sudo apt-get install llvm-15 clang-15

    - name: Install lld
      run: sudo apt-get install lld

    - name: Install libcurl4-openssl-dev
      run: sudo apt-get install libcurl4-openssl-dev

    - run: make
    
  build-macos:
    name: "build on macos-latest"
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - run: brew install llvm@15 && brew link llvm@15

    - run: make
